name: 02 - Trigger on Push
on: []                                             # Run this workflow whenever a push event happens in the repository.

jobs:
  inspect-push:
    runs-on: ubuntu-latest
    steps:
      - name: Echo Commit Metadata
        run: |
          echo "Event: push"
          echo "Target Branch/Ref: $GITHUB_REF"
          echo "Commit SHA: $GITHUB_SHA"
