name: 02 On Push
on: [push]

jobs:
  inspect-push:
    runs-on: ubuntu-latest
    steps:
      - name: Report trigger
        run: echo "Code pushed by ${{ github.actor }} on branch ${{ github.ref_name }}"
