name: 04 Branch and Path Filters
on:
  push:
    branches:
      - main
      - 'release/**'
    paths:
      - 'src/**'
      - 'package.json'
    paths-ignore:
      - '**.md'

jobs:
  filtered-job:
    runs-on: ubuntu-latest
    steps:
      - name: Run code tasks
        run: echo "Triggered because source code in target branches changed"
