name: 08 Runner Context
on: workflow_dispatch

jobs:
  inspect-runner:
    runs-on: ubuntu-latest
    steps:
      - name: Print runner details
        run: |
          echo "OS: ${{ runner.os }}"
          echo "Arch: ${{ runner.arch }}"
          echo "Workspace: ${{ runner.workspace }}"
          echo "Temp Directory: ${{ runner.temp }}"
