name: 10 Checkout Action
on: workflow_dispatch

jobs:
  clone-repo:
    runs-on: ubuntu-latest
    steps:
      - name: Fetch full Git history
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Inspect cloned files
        run: |
          git status
          ls -la
