name: 12 - Environment Variable Scopes
on: workflow_dispatch

env:
  SCOPE: "workflow-level"          # Workflow scope -> visible to all jobs&steps
  STAGE: global
  GLOBAL_FLAG: "true"

jobs1:
  test-scopes:
    runs-on: ubuntu-latest
    env:
      NAME: Test
      SCOPE: "job-level"
    steps:
      - name: Inspect Precedence
        env:
          SCOPE: "step-level"
        run: |
          echo "Current SCOPE (should be 'step-level'): $SCOPE"
          echo "Global flag: $GLOBAL_FLAG"
jobs2:
  build-scopes:
    runs-on: ubuntu-latest
    env:
      SCOPE: "job-level"
    steps:
      - name: Inspect Precedence
        env:
          SCOPE: "step-level"
        run: |
          echo "Current SCOPE (should be 'step-level'): $SCOPE"
          echo "Global flag: $GLOBAL_FLAG"
