name: 17 Needs Dependencies (DAG)
on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Compiling binary"

  unit-test:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Running test suite"

  deploy:
    runs-on: ubuntu-latest
    needs: [build, unit-test] # Must wait for both to pass
    steps:
      - run: echo "Both dependencies succeeded. Deploying..."
