name: 18 If Conditionals
on:
  push:
    branches: [main, dev]
  workflow_dispatch:

jobs:
  branch-check:
    runs-on: ubuntu-latest
    steps:
      - name: Run only on main
        if: github.ref == 'refs/heads/main'
        run: echo "Production branch detected"

      - name: Run only on manual trigger
        if: github.event_name == 'workflow_dispatch'
        run: echo "Manual execution detected"
