name: 19 Status Functions
on: workflow_dispatch

jobs:
  status-demo:
    runs-on: ubuntu-latest
    steps:
      - name: Flaky Step
        run: |
          echo "Simulating failure..."
          exit 1

      - name: Run on failure
        if: failure()
        run: echo "The previous step failed; sending alert."

      - name: Run always
        if: always()
        run: echo "Cleaning up temporary resources regardless of success/failure."
