name: 27 Reusable Workflow Caller
on: workflow_dispatch

jobs:
  call-child:
    # Calls the callee workflow located in the same repository
    uses: ./.github/workflows/28-reusable-workflow-callee.yml
    with:
      target-environment: 'staging'
    secrets: inherit
