name: 32 - Concurrency Controls
on:
  push:
    branches: [main]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true # Cancels running build if a new commit is pushed

jobs:
  long-build:
    runs-on: ubuntu-latest
    steps:
      - name: Simulate Build
        run: |
          echo "Starting slow task..."
          sleep 15
          echo "Finished task."
